### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by dxp10** [mrmalvicino/mrmalvicino.github.io#1]
Hi friend, could you rate my repositories and I'll rate yours at the same time? Thanks!

**Comment by mrmalvicino** [comment]
Im not sure of what you mean by rate. You mean staring?

**Comment by dxp10** [comment]
Yes

**Comment by mrmalvicino** [comment]
¡Ohh I see, lets do it then!

**Comment by dxp10** [comment]
OK. Thanks
